### ISSUE TITLE
Add ITimer.Enabled for running status

### ISSUE THREAD

**Issue by JeremyGEA** [RobThree/ITimer#1]
It would be great to have a boolean value to monitor if the underlying timer is running or not. This could follow Sytem.Timers.Timer.Enabled.

**Comment by RobThree** [comment]
I guess that makes sense. I think a getter (readonly) property would suffice; I don't want to muddy the interface with a setter - I prefer the more explicit `Start()` and `Stop()` methods; would you agree?

**Comment by RobThree** [comment]
[Done](https://github.com/RobThree/ITimer/commit/8deedb5753befe2753a046660be781b935e6ef7c#diff-c060e94f1dd87947c699d48381350c8ec74219ccab88ba54f5b23cdff296c9e1) and released as [1.0.3](https://github.com/RobThree/ITimer/releases/tag/1.0.3) ([NuGet](https://www.nuget.org/packages/ITimer/1.0.3))
