### ISSUE TITLE
How do I raise an event on a mock of ISignaler?

### ISSUE THREAD

**Issue by basprins** [RobThree/ITimer#3]
Hi,

How should I raise an event on a `Mock<ISignaler>` when the `TestTimerElapsedEventArgs` has a protected constructor?

```
            _timerMock = new Mock<ISignaler>();
            _timerMock.Raise(timer => timer.Elapsed += null!, new TestTimerElapsedEventArgs(0, DateTimeOffset.Now));
```

That won't compile for obvious reasons.

Thx

**Comment by RobThree** [comment]
Why don't you use the [`TestTimer`](https://github.com/RobThree/ITimer#testtimer)? That's what it's for.
